### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Arduino_Bootloader#6]
**IDE**

- [x] Burn bootloader on OSX/Windows/Linux
- [x] Upload sketch on OS/Windows/Linux
- [x] Upload sketch with Serial opened on OS/Windows/Linux
- [ ] <strike>Download sketch via OTA with OSX</strike> Reason: missing OTA CLI that support package zip file. 
- [x] Test with latest Arduino IDE  1.8.1 ( tested with 1.6.12)

**MODE**

- [x] **DFU** GND , **FRST** HIGH = Enter **SERIAL** Bootloader
- [x] **DFU** GND, **FRST** GND = Enter **OTA** Bootloader
- [x] **DFU** HIGH, **FRST** LOW = **Factory Reset**, erase Application Code & Application Data then continue to Serial mode.
- [x] DFU Serial entered when there is no valid application code
- [x] DFU Startup:  DFU Serial is automatically entered whenever power on (even without any DFU condition) for 1 seconds for uploading sketch from Arduino IDE 
- [x] Application code can request to enter Serial and upload
- [x] Application code can request to enter OTA and upload
- [x] DFU OTA timeout is 300 seconds ~ 5 minutes 

**INDICATOR**

- [x] DFU Serial : LED_RED is blinking fast (200ms), and 2x (100ms) when uploading
- [x] DFU OTA : LED_RED & LED_BLUE are blinking fast, LED_BLUE stay on when connected, LED_RED blink 2x when uploading
- [x] Factory Reset: RED will blink 2x, BLUE is turn on when erasing (very brief).

**BEHAVIOR**

- [x] DFU OTA, Device Information should have
  - [x] Adv Name is `AdaDFU`
  - [x] Manufacture String is `Adafruit Industries`
  - [x] Model String is `Bluefruit Feather 52`
  - [x] Firmware String is `SDname SDversion, Btldvresion` e.g `S132 2.0.1, 0.5.0`
- [x] DFU (Serial & OTA) reject nrf51 firmware. Note: by only accepting package with device_type = 0x0052
  - such package is generated by `--dev-type 0x0052` option with nrfutil
- [x] DFU OTA only accept Bootloader and/or SoftDevice with secret unlock code with device_rev = 0xADAF
  - such package is generated by `--dev-revision 0xADAF` option with nrfutil
- [x] Update zip file from iOS/Android
- [x] Test upgrading modified current bootloader e.g 0.5.1 + SD132 v2.0.1
- [x] Test upgrading next-gen bootloader + SD132 v3.0.0
